name: Chromatix Actions Builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Build ES Lint
        run: yarn build-eslint
      - name: Build Pull Requests
        run: yarn build-pull-requests
      - name: Commit Files
        run: |
          git config --local user.email "services@chromatix.com.au"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add Built Files" -a
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
